"""Generated from schema: every event and command by its wire type."""

from typing import Literal

from pinecall_protocol._base import WireModel
from pinecall_protocol.commands import (
    AgentConfigure,
    AgentRegister,
    AgentReply,
    AgentSay,
    CallDial,
    CallDtmf,
    CallEvent,
    CallHangup,
    CallHold,
    CallLog,
    CallMute,
    CallTransfer,
    CallUnhold,
    CallUnmute,
    DevAnswer,
    ParticipantMute,
    ParticipantRemove,
    Ping,
    PromptSet,
    RoomInvite,
    RoomSend,
    SessionConfigure,
    StateSet,
    SupervisorVerb,
    ToolsSet,
)
from pinecall_protocol.defs import ToolResult
from pinecall_protocol.events import (
    AgentConfigured,
    AgentDetached,
    AgentRegistered,
    AgentStateChanged,
    AgentTranscript,
    AgentTurnEnded,
    CallbackRequested,
    CallDialing,
    CallEnded,
    CallLine,
    CallRinging,
    CallScore,
    CallStarted,
    CallSummary,
    CallTransferred,
    ConfirmDeclined,
    ConfirmGranted,
    ConfirmRequest,
    CreditsExhausted,
    Custom,
    DevRequest,
    DocsSources,
    ErrorEvent,
    FleetFull,
    LogCaughtUp,
    LogGap,
    MemoryOps,
    Pong,
    PromptChanged,
    StateChanged,
    SupervisorEnded,
    SupervisorReleased,
    SupervisorSaid,
    SupervisorTookOver,
    SupervisorTransferred,
    SupervisorWhispered,
    ToolCall,
    ToolsChanged,
    UserStateChanged,
    UserTranscript,
    UserTurnEnded,
)
from pinecall_protocol.metrics import (
    AvatarMetrics,
    EOTInferenceMetrics,
    EOUMetrics,
    InterruptionMetrics,
    LLMMetrics,
    RealtimeModelMetrics,
    STTMetrics,
    TTSMetrics,
    VADMetrics,
)
from pinecall_protocol.room import (
    EventReceived,
    ParticipantJoined,
    ParticipantLeft,
    ParticipantSpeaking,
    RoomOpened,
    RoomSent,
    TrackPublished,
    TrackUnpublished,
)

# Every event by its wire type; codec looks the model up here.
EVENTS: dict[str, type[WireModel]] = {
    "agent.configured": AgentConfigured,
    "agent.detached": AgentDetached,
    "agent.registered": AgentRegistered,
    "agent.state": AgentStateChanged,
    "agent.transcript": AgentTranscript,
    "call.dialing": CallDialing,
    "call.ended": CallEnded,
    "call.line": CallLine,
    "call.ringing": CallRinging,
    "call.score": CallScore,
    "call.started": CallStarted,
    "call.summary": CallSummary,
    "call.transferred": CallTransferred,
    "callback.requested": CallbackRequested,
    "confirm.declined": ConfirmDeclined,
    "confirm.granted": ConfirmGranted,
    "confirm.request": ConfirmRequest,
    "credits.exhausted": CreditsExhausted,
    "custom": Custom,
    "dev.request": DevRequest,
    "docs.sources": DocsSources,
    "error": ErrorEvent,
    "event.received": EventReceived,
    "fleet.full": FleetFull,
    "log.caught_up": LogCaughtUp,
    "log.gap": LogGap,
    "memory.ops": MemoryOps,
    "metrics.avatar": AvatarMetrics,
    "metrics.eot": EOTInferenceMetrics,
    "metrics.eou": EOUMetrics,
    "metrics.interruption": InterruptionMetrics,
    "metrics.llm": LLMMetrics,
    "metrics.realtime": RealtimeModelMetrics,
    "metrics.stt": STTMetrics,
    "metrics.tts": TTSMetrics,
    "metrics.vad": VADMetrics,
    "participant.joined": ParticipantJoined,
    "participant.left": ParticipantLeft,
    "participant.speaking": ParticipantSpeaking,
    "pong": Pong,
    "prompt.changed": PromptChanged,
    "room.opened": RoomOpened,
    "room.sent": RoomSent,
    "state.changed": StateChanged,
    "supervisor.ended": SupervisorEnded,
    "supervisor.released": SupervisorReleased,
    "supervisor.said": SupervisorSaid,
    "supervisor.took_over": SupervisorTookOver,
    "supervisor.transferred": SupervisorTransferred,
    "supervisor.whispered": SupervisorWhispered,
    "tool.call": ToolCall,
    "tool.result": ToolResult,
    "tools.changed": ToolsChanged,
    "track.published": TrackPublished,
    "track.unpublished": TrackUnpublished,
    "turn.agent": AgentTurnEnded,
    "turn.user": UserTurnEnded,
    "user.state": UserStateChanged,
    "user.transcript": UserTranscript,
}

type EventType = Literal[
    "agent.configured",
    "agent.detached",
    "agent.registered",
    "agent.state",
    "agent.transcript",
    "call.dialing",
    "call.ended",
    "call.line",
    "call.ringing",
    "call.score",
    "call.started",
    "call.summary",
    "call.transferred",
    "callback.requested",
    "confirm.declined",
    "confirm.granted",
    "confirm.request",
    "credits.exhausted",
    "custom",
    "dev.request",
    "docs.sources",
    "error",
    "event.received",
    "fleet.full",
    "log.caught_up",
    "log.gap",
    "memory.ops",
    "metrics.avatar",
    "metrics.eot",
    "metrics.eou",
    "metrics.interruption",
    "metrics.llm",
    "metrics.realtime",
    "metrics.stt",
    "metrics.tts",
    "metrics.vad",
    "participant.joined",
    "participant.left",
    "participant.speaking",
    "pong",
    "prompt.changed",
    "room.opened",
    "room.sent",
    "state.changed",
    "supervisor.ended",
    "supervisor.released",
    "supervisor.said",
    "supervisor.took_over",
    "supervisor.transferred",
    "supervisor.whispered",
    "tool.call",
    "tool.result",
    "tools.changed",
    "track.published",
    "track.unpublished",
    "turn.agent",
    "turn.user",
    "user.state",
    "user.transcript",
]


# Events a store may drop and a slow reader may miss: the entry's ephemeral flag defaults
# to this.
EPHEMERAL_EVENTS: frozenset[str] = frozenset(
    {
        "agent.transcript",
        "dev.request",
        "log.caught_up",
        "log.gap",
        "metrics.vad",
        "participant.speaking",
        "pong",
        "room.sent",
        "user.transcript",
    }
)


# The one event that ends a call: after it nothing more is true and the log is sealed.
TERMINAL_EVENT: str = "call.score"


# Every command by its wire type; codec looks the model up here.
COMMANDS: dict[str, type[WireModel]] = {
    "agent.configure": AgentConfigure,
    "agent.register": AgentRegister,
    "agent.reply": AgentReply,
    "agent.say": AgentSay,
    "call.dial": CallDial,
    "call.dtmf": CallDtmf,
    "call.event": CallEvent,
    "call.hangup": CallHangup,
    "call.hold": CallHold,
    "call.log": CallLog,
    "call.mute": CallMute,
    "call.transfer": CallTransfer,
    "call.unhold": CallUnhold,
    "call.unmute": CallUnmute,
    "dev.answer": DevAnswer,
    "participant.mute": ParticipantMute,
    "participant.remove": ParticipantRemove,
    "ping": Ping,
    "prompt.set": PromptSet,
    "room.invite": RoomInvite,
    "room.send": RoomSend,
    "session.configure": SessionConfigure,
    "state.set": StateSet,
    "supervisor.verb": SupervisorVerb,
    "tool.result": ToolResult,
    "tools.set": ToolsSet,
}

type CommandType = Literal[
    "agent.configure",
    "agent.register",
    "agent.reply",
    "agent.say",
    "call.dial",
    "call.dtmf",
    "call.event",
    "call.hangup",
    "call.hold",
    "call.log",
    "call.mute",
    "call.transfer",
    "call.unhold",
    "call.unmute",
    "dev.answer",
    "participant.mute",
    "participant.remove",
    "ping",
    "prompt.set",
    "room.invite",
    "room.send",
    "session.configure",
    "state.set",
    "supervisor.verb",
    "tool.result",
    "tools.set",
]


# Which events a command lands in the log as, so a caller knows what to wait for.
PRODUCES: dict[str, tuple[str, ...]] = {
    "agent.configure": ("agent.configured",),
    "agent.register": ("agent.registered",),
    "agent.reply": ("turn.agent",),
    "agent.say": ("turn.agent",),
    "call.dial": ("call.dialing",),
    "call.dtmf": (),
    "call.event": ("event.received",),
    "call.hangup": ("call.ended",),
    "call.hold": ("call.line",),
    "call.log": ("custom",),
    "call.mute": ("call.line",),
    "call.transfer": ("call.transferred",),
    "call.unhold": ("call.line",),
    "call.unmute": ("call.line",),
    "dev.answer": (),
    "participant.mute": ("track.unpublished",),
    "participant.remove": ("participant.left",),
    "ping": ("pong",),
    "prompt.set": ("prompt.changed",),
    "room.invite": ("participant.joined",),
    "room.send": ("room.sent",),
    "session.configure": ("state.changed", "agent.configured"),
    "state.set": ("state.changed",),
    "supervisor.verb": (
        "supervisor.said",
        "supervisor.whispered",
        "supervisor.took_over",
        "supervisor.released",
        "supervisor.transferred",
        "supervisor.ended",
    ),
    "tool.result": ("tool.result",),
    "tools.set": ("tools.changed",),
}
